### PR TITLE
Fix accessibility and user settings bugs

### LINKED ISSUE #147: [Bug]: At max Text size value, "Directions" doesn's fit in the bottom menu
### Bug Description

At max Text size value, "Directions" doesn's fit in the bottom menu

### Steps to Reproduce

1. Got to accesibilty
2. Set the Font size to the Maximum
3. Go back to the main page
4. "Directions" doesn't fit

### Expected Behavior

I expected all the text to get bigger without the "S" in directions wrapping to a new line

### Actual Behavior

The "s" is push to a new line

### Screenshots

Image

### Device Type

Android Phone

### Device Model

Google Pixel 8

### OS Version

Andoid 16

### Severity

Low - Minor issue or cosmetic problem

### Additional Context

_No response_

### LINKED ISSUE #148: [Bug]:  User settings page renders too high when accessed from map screen, blocking back button
### Bug Description

 When accessing the user settings page via the Account (A) icon from the map screen, the page content is positioned too high, overlapping the back button and making it  
  inaccessible. However, when accessing the same page from the home screen before navigating to the map, it renders correctly with proper spacing.

### Steps to Reproduce

 1. Launch the app and navigate to the map screen                                                                                                                        
  2. Tap the Account icon (A icon) in the top bar on the map screen                                                                                                       
  3. Observe the user settings page opens with content positioned too high                                                                                                
  4. Attempt to tap the back button - it is not clickable                                                                                                                 
  5. Restart the app                                                                                                                                                      
  6. From the home screen, access the user settings page directly (before going to map)                                                                                   
  7. Observe the page renders correctly with proper spacing and clickable back button

### Expected Behavior

 The user settings page should render consistently with proper top padding and spacing regardless of which screen it is accessed from. The back button should always be  
  visible and clickable. Accessing the page from the map screen should produce the same layout as accessing it from the home screen.   

### Actual Behavior

  The user settings page renders differently based on navigation path:                                                                                                    
  - When accessed FROM MAP: Content is too high, overlapping the back button, making it inaccessible                                                                      
  - When accessed FROM HOME: Content renders correctly with proper spacing and functional back button

   Users are trapped on the settings page when accessing it from the map with no way to navigate back.  

### Screenshots

<img width="1080" height="2424" alt="Image" src="https://github.com/user-attachments/assets/527e96c5-2020-48c3-8316-a4c33bcefd57" />

### Device Type

Android Phone

### Device Model

 Pixel 9A (Emulator)

### OS Version

  Android 14

### App Version

1.0

### Severity

High - Major feature is broken

### Additional Context

 This bug only occurs when navigating to the user settings page from the map screen via the Account (A) icon. The same page works correctly when accessed from the home  
  screen, indicating a navigation or composition context issue.                                                                                                           
                                                                                                                                                                          
  Likely causes:                                                                                                                                                          
  - Different navigation routes applying different window insets or padding                                                                                               
  - Map screen not properly passing composition locals (window insets)                                                                                                    
  - Scaffold or top bar configuration differs between navigation paths                                                                                                    
  - System bars padding not being applied consistently across navigation contexts                                                                                         
                                                                                                                                                                          
  Files to investigate:                                                                                                                                                   
  - Navigation graph - check if different routes have different configurations                                                                                            
  - MapsActivity.kt - check how navigation to settings is handled                                                                                                         
  - User settings screen composable - check if it relies on parent composition context                                                                                    
  - MainActivity.kt - compare how settings is accessed from home vs map                                                                                                   
                                                                                                                                                                          
  This appears to be a state composition or navigation context bug rather than a layout bug in the settings screen itself.

### LINKED ISSUE #173: [Bug]: User settings does not save after closing app
### Bug Description

After changing the settings and closing the app, when you reopen it, the user settings go back to default.

### Steps to Reproduce

1. Open the app
2. Go to the accessibility screen
3. Change the settings
4. Close the app
5. Relaunch the app

### Expected Behavior

After relaunch, the app should display the user settings as they were before closing it, not the default settings set for when you first open the app.

### Actual Behavior

After relaunch, the app displays the default user settings despite having just changed the font size, bold text or colorblind mode.

### Screenshots

Before closing the app
Image
After reopening the app
Image

### Device Type

Android Phone

### Device Model

Emulated Pixel 9a

### OS Version

Android 16

### App Version

Release 1

### Severity

Medium - Feature works but with issues

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by adamoug**
## Summary
Addresses three critical bugs related to accessibility features and user settings in the app. These fixes improve the user experience for users relying on accessibility features.

### User settings persistence
- Implemented proper data persistence for user settings using SharedPreferences/DataStore
- Ensured settings are saved immediately when changed
- Added proper initialization to load saved settings on app launch
### User settings page layout from map screen
- Ensured consistent Scaffold configuration across different navigation paths
- Applied proper system bars padding that works regardless of navigation context
- Verified back button is accessible from all navigation routes
### Text overflow in bottom menu at maximum font size
- Implemented proper text scaling constraints
- Ensured all navigation labels remain readable and properly formatted

## Notes
Also included updating the rest of the UI so accessibility settings are applied everywhere

## Issues Closed
Closes #173  
Closes #148  
Closes #147

### CODE REVIEW

File: app/src/main/java/com/example/campusguide/ui/screens/AccessibilityScreen.kt [hunk 1]
```diff
@@ -51,6 +56,19 @@ fun AccessibilityScreen(
 ) {
     var isBoldEnabled by remember { mutableStateOf(true) }
     val accessibilityState = LocalAccessibilityState.current
+    val context = LocalContext.current
+    val scope = rememberCoroutineScope()
+
+    fun persist() {
```
Comment (anhvimac) [inline app/src/main/java/com/example/campusguide/ui/screens/AccessibilityScreen.kt]: Maybe you can move this persist() function into the AccessibilityState methods instead of having it in every onClick? If we can centralize it in the state class, the ui won't need to worry about the saving logic. It will make the onclicks simpler and we wont forget to call it if we add accessibility settings on other screens later. This will also help avoid duplicate code too.
